api/Web.Fox/Pages/Menu/DocumentPermission.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fox.Access.Service;
using FoxUser = Fox.Access.Model.User;
using FoxGroup = Fox.Access.Model.Group;
using Fox.Dox.Service;
using Fox.Dox.Model;
using Microsoft.AspNetCore.Authorization;
using Fox.Access.Model;

namespace Web.Fox.Pages.Menu;

[Authorize(Policy = "DOCUMENT_PERMISSION_READ")]
public class DocumentPermissionModel : PageModel
{
    [BindProperty]
    public Guid DocumentId { get; set; }
    [BindProperty]
    public string DocumentName { get; set; } = string.Empty;
    [BindProperty]
    public string HolderType { get; set; } = string.Empty;

    [FromQuery(Name = "documentId")]
    public Guid DocumentIdQuery { get; set; }
    [FromQuery(Name = "documentName")]
    public string DocumentNameQuery { get; set; } = string.Empty;
    [FromQuery(Name = "holderType")]
    public string HolderTypeQuery { get; set; } = string.Empty;

    public string Msg { get; set; } = string.Empty;
    public IEnumerable<DocumentHolder> PermissionsGiven { get; set; } = Array.Empty<DocumentHolder>();
    public IEnumerable<DocumentHolder> PermissionsDenied { get; set; } = Array.Empty<DocumentHolder>();

    private DocumentService _docService;
    private GroupService _groupService;
    private UserService _userService;
    public DocumentPermissionModel(DocumentService docService, GroupService groupService, UserService userService)
    {
        _docService = docService;
        _groupService = groupService;
        _userService = userService;
    }

    private void FillPermissionsList()
    {
        PermissionsGiven = _docService.GetPermissionByDocument(DocumentId)
                                   .Where(p => p.HolderType.ToLower() == HolderType.ToLower())
                                   .OrderBy(p => p.Permission)
                                   .ThenBy(p => p.HolderName);
        if (HolderType.ToLower() == "user")
        {
            PermissionsDenied = _userService.GetAllUsers()
                                         .Select(user => new DocumentHolder()
                                         {
                                             HolderId = user.Id,
                                             HolderLogin = user.Login,
                                             HolderName = user.Name,
                                             HolderType = "user"
                                         });
        }
        else
        {
            PermissionsDenied = _groupService.GetAllGroups()
                                          .Select(group => new DocumentHolder()
                                          {
                                              HolderId = group.Id,
                                              HolderName = group.Name,
                                              HolderType = "group"
                                          });
        }
        PermissionsDenied = PermissionsDenied.Where(p => !PermissionsGiven.Any(g => g.HolderId == p.HolderId))
                                             .OrderBy(p => p.HolderName);
    }

    public void OnGet()
    {
        DocumentId = DocumentIdQuery;
        DocumentName = DocumentNameQuery;
        HolderType = HolderTypeQuery;
        FillPermissionsList();
    }

    public void OnPostAddPermission(Guid holderId, DocumentPermission permission)
    {
        try
        {
            HttpContext.HasPermission("DOCUMENT_PERMISSION_ADDITION");
            _docService.AddPermission(DocumentId, holderId, permission);
        }
        catch(Exception argEx)
        {
            Msg = argEx.Message;
        }
        FillPermissionsList();
    }

    public void OnPostDelPermission(Guid holderId, DocumentPermission permission)
    {
        try
        {
            HttpContext.HasPermission("DOCUMENT_PERMISSION_REMOVAL");
            _docService.DelPermission(DocumentId, holderId, permission);
        }
        catch (Exception argEx)
        {
            Msg = argEx.Message;
        }
        FillPermissionsList();
    }
}

api/Web.Fox/Pages/Menu/DownloadDocument.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fox.Dox.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fox.Dox.Model;
using Microsoft.AspNetCore.Authorization;

namespace Web.Fox.Pages.Menu;

[Authorize(Policy = "DOCUMENT_READ")]
public class DownloadDocumentModel : PageModel, INavBarItem
{
    public string MenuDescription => "Download";
    public string PagePath => "/Menu/DownloadDocument";
    public string MenuCategory => "DOCUMENT";

    public string Msg { get; set; } = string.Empty;
    public IEnumerable<DocumentInformation> Documents { get; set; } = Array.Empty<DocumentInformation>();

    public IEnumerable<DocumentHolder> DocumentHolders { get; set; } = Array.Empty<DocumentHolder>();

    [BindProperty]
    public Guid? HoldersFor { get; set; }
    
    private DocumentService _docService;
    public DownloadDocumentModel(DocumentService docService)
    {
        _docService = docService;
    }

    private void FillDocuments()
    {
        Documents = _docService.GetAllDocuments();
        foreach (var item in Documents)
        {
            DocumentInformation? docWithMetadata = _docService.GetDocumentInformation(item.Id);
            if(docWithMetadata != null)
                item.Metadata = docWithMetadata.Metadata;
        }
        Documents = Documents.OrderBy(d => d.Name);
    }

    public void OnGet()
    {
        FillDocuments();
    }

    public void OnPostDeleteDocument(Guid documentId)
    {
        try
        {
            HttpContext.HasPermission("DOCUMENT_DELETION");
            _docService.DeleteDocument(documentId);
        }
        catch (ArgumentException argEx)
        {
            Msg = argEx.Message;
        }
        FillDocuments();
    }

    public void OnPostHolders(Guid documentId)
    {
        try
        {
            HttpContext.HasPermission("DOCUMENT_PERMISSION_READ");
            DocumentHolders = _docService.GetPermissionByDocument(documentId);
            HoldersFor = documentId;
        }
        catch (Exception argEx)
        {
            Msg = argEx.Message;
        }
        FillDocuments();
    }

    public async Task<IActionResult> OnPostDownloadAsync(Guid documentId, string documentName)
    {
        try
        {
            HttpContext.HasPermission("DOCUMENT_READ");
            var file = await _docService.GetDocumentBinaryAsync(documentId);
            FillDocuments();
            return File(file, "application/octet-stream", documentName);
        }
        catch (ArgumentException argEx)
        {
            Msg = argEx.Message;
            FillDocuments();
            return Page();
        }
    }
}

api/Web.Fox/Pages/Menu/GroupManagement.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fox.Access.Service;
using Fox.Access.Model;
using Microsoft.AspNetCore.Authorization;

namespace Web.Fox.Pages.Menu;

[Authorize(Policy = "GROUP_READ_ALL_MANAGEMENT")]
public class GroupManagementModel : PageModel, INavBarItem
{
    public string MenuDescription => "Groups";
    public string PagePath => "/Menu/GroupManagement";
    public string MenuCategory => "MANAGEMENT";

    public bool SuccessOnPost { get; set; } = true;
    public string Msg { get; set; } = string.Empty;
    private IEnumerable<Group> _groups = Array.Empty<Group>();
    public IEnumerable<Group> Groups
    {
        get => _groups.OrderBy(g => g.Name);
        set => _groups = value;
    }

    [BindProperty]
    public Guid? AlterModeFor { get; set; }
    [BindProperty]
    public string AlterModeNewGroupName { get; set; } = string.Empty;
    [BindProperty]
    public string CreateNewGroupName { get; set; } = string.Empty;

    private GroupService _groupService;
    public GroupManagementModel(GroupService groupService)
    {
        _groupService = groupService;
    }

    public void OnGet()
    {
        Groups = _groupService.GetAllGroups();
    }

    public void OnPostEnterUpdateMode(Guid groupId)
    {
        Groups = _groupService.GetAllGroups();
        AlterModeFor = groupId;
    }

    public void OnPostDeleteGroup(Guid groupId)
    {
        try
        {
            HttpContext.HasPermission("GROUP_DELETION_MANAGEMENT");
            _groupService.DeleteGroup(groupId);
            SuccessOnPost = true;
        }
        catch (ArgumentException argEx)
        {
            Msg = argEx.Message;
            SuccessOnPost = false;
        }
        Groups = _groupService.GetAllGroups();
    }

    public void OnPostUpdateGroup(Guid groupId)
    {
        try
        {
            HttpContext.HasPermission("GROUP_UPDATE_MANAGEMENT");
            _groupService.UpdateGroup(new Group()
            {
                Id = groupId,
                Name = AlterModeNewGroupName
            });
            AlterModeFor = null;
            SuccessOnPost = true;
        }
        catch(Exception argEx)
        {
            Msg = argEx.Message;
            SuccessOnPost = false;
        }
        Groups = _groupService.GetAllGroups();
    }

    public IActionResult OnPostCreateGroup()
    {
        try
        {
            HttpContext.HasPermission("GROUP_CREATION_MANAGEMENT");
            _groupService.CreateGroup(new Group()
            {
                Name = CreateNewGroupName
            });
            Msg = "Group created!";
            CreateNewGroupName = string.Empty;
            SuccessOnPost = true;
        }
        catch (Exception argEx)
        {
            Msg = argEx.Message;
            SuccessOnPost = false;
        }
        Groups = _groupService.GetAllGroups();
        return Page();
    }

    public void OnPostCancelUpdate()
    {
        AlterModeFor = null;
        Groups = _groupService.GetAllGroups();
    }
}

api/Web.Fox/Pages/Menu/GroupUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fox.Access.Service;
using Fox.Access.Model;
using FoxUser = Fox.Access.Model.User;
using Microsoft.AspNetCore.Authorization;

namespace Web.Fox.Pages.Menu;

[Authorize(Policy = "GROUP_MANAGEMENT_READ_USER")]
public class GroupUserModel : PageModel
{
    [BindProperty]
    public Guid GroupId { get; set; }
    [BindProperty]
    public string GroupName { get; set; } = string.Empty;

    [FromQuery(Name = "groupId")]
    public Guid GroupIdQuery { get; set; }
    [FromQuery(Name = "groupName")]
    public string GroupNameQuery { get; set; } = string.Empty;

    public string Msg { get; set; } = string.Empty;
    public IEnumerable<FoxUser> UsersInGroup { get; set; } = Array.Empty<FoxUser>();
    public IEnumerable<FoxUser> UsersNotInGroup { get; set; } = Array.Empty<FoxUser>();

    private UserService _userService;
    private GroupService _groupService;
    public GroupUserModel(GroupService groupService, UserService userService)
    {
        _groupService = groupService;
        _userService = userService;
    }

    private void FillUsersList()
    {
        UsersInGroup = _groupService.GetUsersFromGroup(GroupId).OrderBy(u => u.Name);
        UsersNotInGroup = _userService.GetAllUsers()
                                   .Where(u => !UsersInGroup.Any(ug => ug.Id == u.Id))
                                   .OrderBy(u => u.Name);
    }

    public void OnGet()
    {
        GroupId = GroupIdQuery;
        GroupName = GroupNameQuery;
        FillUsersList();
    }

    public void OnPostAddToGroup(Guid userId)
    {
        try
        {
            HttpContext.HasPermission("GROUP_MANAGEMENT_ADDUSER");
            _groupService.AddUserToGroup(GroupId, new Guid[] { userId });
        }
        catch(Exception argEx)
        {
            Msg = argEx.Message;
        }
        FillUsersList();
    }

    public void OnPostDelFromGroup(Guid userId)
    {
        try
        {
            HttpContext.HasPermission("GROUP_MANAGEMENT_DELUSER");
            _groupService.DelUserFromGroup(GroupId, new Guid[] { userId });
        }
        catch (Exception argEx)
        {
            Msg = argEx.Message;
        }
        FillUsersList();
    }
}

api/Web.Fox/Pages/Menu/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fox.Access.Service;
using Fox.Access.Model;
using FoxUser = Fox.Access.Model.User;
using Microsoft.AspNetCore.Authorization;

namespace Web.Fox.Pages.Menu;

[Authorize(Policy = "USER_SELF_MANAGEMENT")]
public class ProfileModel : PageModel, INavBarItem
{
    public string MenuDescription => "Profile";
    public string PagePath => "/Menu/Profile";
    public LoggedUser LoggedUser { get; set; }
    public string MenuCategory => "SELF_MANAGEMENT";

    UserService _userService;
    public ProfileModel(UserService userService, LoggedUser loggedUser)
    {
        _userService = userService;
        LoggedUser = loggedUser;
    }

    public bool SuccessOnPost { get; set; } = true;
    public string MsgInformation { get; set; } = string.Empty;
    public string MsgPassword { get; set; } = string.Empty;
    [BindProperty]
    public UserModel UserData { get; set; } = new UserModel();

    public void OnGet()
    {
        var currentUserInformation = _userService.GetUser(LoggedUser.Id);
        if (currentUserInformation == null)
            return;
        UserData.Login = currentUserInformation.Login;
        UserData.Email = currentUserInformation.Email;
        UserData.Name = currentUserInformation.Name;
    }

    public void OnPostUserInformation()
    {
        try
        {
            _userService.UpdateUser(new FoxUser()
            {
                Id = LoggedUser.Id,
                Login = UserData.Login,
                Name = UserData.Name,
                Email = UserData.Email
            });
            SuccessOnPost = true;
            MsgInformation = "Information updated!";
        }
        catch(Exception argEx)
        {
            MsgInformation = argEx.Message;
            SuccessOnPost = false;
        }
    }

    public void OnPostChangePassword()
    {
        try
        {
            if(UserData.Password != UserData.PasswordConfirmation)
            {
                throw new ArgumentException("The password confirmation do not match");
            }
            _userService.UpdatePassword(LoggedUser.Id, UserData.Password);
            MsgPassword = "Password changed!";
            SuccessOnPost = true;
        }
        catch (Exception argEx)
        {
            MsgPassword = argEx.Message;
            SuccessOnPost = false;
        }
    }
}

public class UserModel
{
    public string Login { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public string PasswordConfirmation { get; set; } = string.Empty;
}

api/Web.Fox/Pages/Menu/UploadDocument.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fox.Access.Service;
using Fox.Dox.Service;
using Fox.Access.Model;
using Fox.Dox.Model;
using FoxUser = Fox.Access.Model.User;
using Microsoft.AspNetCore.Authorization;

namespace Web.Fox.Pages.Menu;

[Authorize(Policy = "DOCUMENT_CREATION")]
public class UploadDocumentModel : PageModel, INavBarItem
{
    public string MenuDescription => "Upload";
    public string PagePath => "/Menu/UploadDocument";
    public string MenuCategory => "DOCUMENT";
    public LoggedUser LoggedUser { get; set; }

    DocumentService _docService;
    public UploadDocumentModel(DocumentService docService, LoggedUser loggedUser)
    {
        _docService = docService;
        LoggedUser = loggedUser;
    }

    public bool SuccessOnPost { get; set; } = true;
    public string MsgInformation { get; set; } = string.Empty;
    [BindProperty]
    public IFormFile? FileBinary { get; set; }

    public void OnGet()
    {
        
    }

    public async Task<IActionResult> OnPostUploadDocumentAsync(List<MetadataModel> metadata)
    {
        try
        {
            if (FileBinary == null)
                throw new ArgumentException("No file was selected");

            var document = new DocumentInformation()
            {
                Name = FileBinary.FileName,
                Metadata = new Dictionary<string, string>()
            };
            foreach (var item in metadata.Where(m => !string.IsNullOrWhiteSpace(m.Key)))
                document.Metadata.Add(item.Key, item.Value);

            using (var ms = new MemoryStream())
            {
                FileBinary.CopyTo(ms);
                await _docService.CreateDocumentAsync(document, ms);
            }

            SuccessOnPost = true;
            MsgInformation = "Document uploaded!";
            return RedirectToPage("DownloadDocument");
        }
        catch(Exception argEx)
        {
            MsgInformation = argEx.Message;
            SuccessOnPost = false;
            return Page();
        }
    }
}

public class MetadataModel
{
    public string Key { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
}

api/Web.Fox/Pages/Menu/DownloadDocument.cshtml
@page
@model Web.Fox.Pages.Menu.DownloadDocumentModel
@{
    Layout = "../_Layout";
    ViewBag.Title = "Documents";
}

<main class="form-signin w-100 vh-100">
    @if (!string.IsNullOrEmpty(Model.Msg))
    {
        <div class="alert alert-danger mb-1" role="alert">
            @Model.Msg
        </div>
    }
    <form method="post">
        <div class="w-100 row">
            <div class="card p-5 bg-light w-50 col">
                <h1 class="h3 mb-3 fw-normal text-center">Documents</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Metadata</th>
                            <th scope="col">File Size</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var document in Model.Documents)
                        {
                            <tr>
                                <td>@document.Name</td>
                                <td>
                                    <table class="table">
                                        <tbody>
                                            @foreach (var metadata in document.Metadata)
                                            {
                                                <tr>
                                                    <td>@metadata.Key</td>
                                                    <td>@metadata.Value</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                                <td>@($"{(document.FileSizeBytes / 1024d / 1024d):f3}")mb</td>
                                <td>
                                    <a class="btn btn-primary" type="submit" asp-page="UpdateDocument" asp-route-documentId="@document.Id" asp-route-documentName="@document.Name">Alter</a>&nbsp;
                                    <button class="btn btn-primary" type="submit" asp-page-handler="Holders" asp-route-documentId="@document.Id">Holders</button>&nbsp;
                                    <button class="btn btn-primary" type="submit" asp-page-handler="Download" asp-route-documentId="@document.Id" asp-route-documentName="@document.Name">Download</button>&nbsp;
                                    <button class="btn btn-danger" type="submit" asp-page-handler="DeleteDocument" asp-route-documentId="@document.Id">Delete</button>&nbsp;
                                </td>
                            </tr>
                            if(Model.HoldersFor == document.Id)
                            {
                                <tr>
                                    <td colspan="4">
                                        @if (Model.DocumentHolders.Count() == 0)
                                        {
                                            <p>Only admin users have access to this document</p>
                                        }
                                        else if (Model.DocumentHolders.Count() >= 1)
                                        {
                                            <p>This document can be accessed by:</p>
                                            <table class="table mt-1">
                                                <thead>
                                                    <tr>
                                                        <th>Holder Name</th>
                                                        <th>Holder Type</th>
                                                        <th>Access to</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var holder in Model.DocumentHolders)
                                                    {
                                                        <tr>
                                                            <td>@holder.HolderName</td>
                                                            <td>@holder.HolderType</td>
                                                            <td>@holder.Permission.ToString()</td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        }
                                    <div class="d-flex mb-5 justify-content-end">
                                        <a class="btn btn-info" type="submit" asp-page="DocumentPermission" asp-route-documentId="@document.Id" asp-route-documentName="@document.Name" asp-route-holderType="Group">Manage permissions for Groups</a> &nbsp;
                                        <a class="btn btn-info" type="submit" asp-page="DocumentPermission" asp-route-documentId="@document.Id" asp-route-documentName="@document.Name" asp-route-holderType="User">Manage permissions for Users</a>
                                    </div>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</main>

api/Web.Fox/Pages/Menu/GroupManagement.cshtml
@page
@model Web.Fox.Pages.Menu.GroupManagementModel
@{
    Layout = "../_Layout";
    ViewBag.Title = "Groups";
}

<main class="form-signin w-50 vh-100 mx-auto">
    @if (!string.IsNullOrEmpty(Model.Msg))
    {
        <div class="alert @(Model.SuccessOnPost ? "alert-success" : "alert-danger") mb-1" role="alert">
            @Model.Msg
        </div>
    }
    <form method="post">
        <div class="w-100 row">
            <div class="card p-5 bg-light w-75 col">
                <h1 class="h3 mb-3 fw-normal text-center">Groups</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var group in Model.Groups)
                        {
                            if (Model.AlterModeFor == null)
                            {
                                <tr>
                                    <td>@group.Name</td>
                                    <td>
                                        <button class="btn btn-primary" type="submit" asp-page-handler="EnterUpdateMode" asp-route-groupId="@group.Id">Alter</button>&nbsp;
                                        <a class="btn btn-primary" asp-page="GroupUser" asp-route-groupId="@group.Id" asp-route-groupName="@group.Name">Users</a>&nbsp;
                                        <a class="btn btn-primary" asp-page="SystemPermission" asp-route-holderId="@group.Id" asp-route-holderName="@group.Name" asp-route-holderType="group">Permissions</a>&nbsp;
                                        <button class="btn btn-danger" type="submit" asp-page-handler="DeleteGroup" asp-route-groupId="@group.Id">Delete</button>&nbsp;
                                    </td>
                                </tr>
                            }
                            else
                            {
                                if (Model.AlterModeFor == group.Id)
                                {
                                    <tr>
                                        <td><input class="form-control" type="text" asp-for="AlterModeNewGroupName" id="groupNewName" value="@group.Name" /></td>
                                        <td>
                                            <button class="btn btn-primary" type="submit" asp-page-handler="UpdateGroup" asp-route-groupId="@group.Id">Confirm</button>&nbsp;
                                            <button class="btn btn-danger" type="submit" asp-page-handler="CancelUpdate" asp-route-groupId="@group.Id">Cancel</button>&nbsp;
                                        </td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td>@group.Name</td>
                                        <td>
                                            <button class="btn btn-primary disabled">Alter</button>&nbsp;
                                            <button class="btn btn-primary disabled">Users</button>&nbsp;
                                            <button class="btn btn-primary disabled">Permissions</button>&nbsp;
                                            <button class="btn btn-danger disabled">Delete</button>&nbsp;
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
                @if (Model.AlterModeFor == null)
                {
                    <div class="mt-3 d-flex justify-content-end">
                        <div class="form-floating">
                            <input class="form-control" type="text" asp-for="CreateNewGroupName" placeholder="creategroupname" id="creategroupname" />
                            <label for="creategroupname">New group name</label>
                        </div>
                        &nbsp;
                        <button class="btn btn-info" type="submit" asp-page-handler="CreateGroup" style="max-width: 130px">Create Group</button>
                    </div>
                }
            </div>
        </div>
    </form>
</main>

api/Web.Fox/Pages/Menu/GroupUser.cshtml
@page
@model Web.Fox.Pages.Menu.GroupUserModel
@{
    Layout = "../_Layout";
    ViewBag.Title = "Groups";
}

<main class="form-signin w-100 vh-100" >
    @if (!string.IsNullOrEmpty(Model.Msg))
    {
        <div class="alert alert-danger mb-1" role="alert">
            @Model.Msg
        </div>
    }
<form method="post">
    <input type="hidden" asp-for="GroupId" />
    <input type="hidden" asp-for="GroupName" />
    <div class="w-75 mx-auto">
        <div class="card p-5 bg-light w-100 col">
            <h1 class="h3 mb-3 fw-normal text-center">@Model.GroupName</h1>
            <div class="row">
                <div class="col">
                    <h1 class="h5 mb-3 fw-normal">Users not in the group</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Login</th>
                                <th scope="col">User Name</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var user in Model.UsersNotInGroup)
                            {
                                <tr>
                                    <td>@user.Login</td>
                                    <td>@user.Name</td>
                                    <td>
                                        <button class="btn btn-primary" type="submit" asp-page-handler="AddToGroup" asp-route-userId="@user.Id">Add</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="col border-start">
                    <h1 class="h5 mb-3 fw-normal">Users in the group</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">User Login</th>
                                <th scope="col">User Name</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var user in Model.UsersInGroup)
                            {
                                <tr>
                                    <td>@user.Login</td>
                                    <td>@user.Name</td>
                                    <td>
                                        <button class="btn btn-danger" type="submit" asp-page-handler="DelFromGroup" asp-route-userId="@user.Id">Del</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row d-flex justify-content-end">
                <a class="btn btn-secondary" asp-page="GroupManagement" style="max-width: 100px" >Go Back</a>
            </div>
        </div>
    </div>
</form>
</main>